# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: goea
email: eg@goez.my.id
description: > # this means to ignore newlines until "baseurl:"
  Just another blog goez ea 😘 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://goez.ga" # the base hostname & protocol for your site
permalink: /:title.xhtml
twitter_username: eggoez
github_username:  eggoez

# Build settings
markdown: kramdown
